kind: pipeline
name: deploy

steps:
    - name: unit-test
      image: node:10
      commands:
      - node "test/index.js"
      when:
          branch: single-person
          event: push
    - name: build-image
      image: pulgins/docker
      settings:
          repo: atom.registry.atomcjx.top:30500/hello-ci
          atuo_tag: true
      when:
          event: tag
    
