kind: pipeline
name: deploy

steps:
    - name: unit-test
      image: node:10
      commands:
      - node "test/index.js"
      when:
          branch: single-person
          event: push
    
    - name: build-image
      image: plugins/docker
      settings:
          repo: cuijx/hello-ci
          password:
              from_secret: DOCKER_SECRET
          atuo_tag: true
      when:
          event: tag
    
