kind: pipeline
name: deploy

steps:
    - name: unit-test
      image: node:10
      commands:
      - node "test/index.js"
      when:
          branch: single-person
          event: push
    
    - name: build-image
      image: pulgins/docker
      settings:
          repo: registry.atomcjx.top:30579/hello-ci
          password:
              from_secret: REGISTRY_CRT
          atuo_tag: true
      when:
          event: tag
    
